=== DanielJosefKrueger/IntechPraktikum/InTech22/VML.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:simpleType name="prozent">
		<xsd:restriction base="xsd:decimal">
			<xsd:minInclusive value="0" />
			<xsd:maxInclusive value="100" />
			<xsd:fractionDigits value="2" />
		</xsd:restriction>
	</xsd:simpleType>



	<xsd:element name="Wahl">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Wahltag" type="xsd:date" />
				<xsd:element name="Wahlbeginn" type="xsd:time" />
				<xsd:element name="Wahlende" type="xsd:time" />
				<xsd:element name="Parteien" minOccurs="2"
					maxOccurs="100">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="Name" type="xsd:string" />
							<xsd:element name="Kandidaten" minOccurs="3"
								maxOccurs="25">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="Name" type="xsd:string" />
										<xsd:element name="Geburtsdatum" type="xsd:date" />
										<xsd:element name="Beruf" type="xsd:string"
											minOccurs="0" maxOccurs="1" />
										<xsd:element name="Listenplatz" type="xsd:integer" />
										<xsd:element name="Erststimmen" type="prozent" />
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="Wahlergebnis">
					<xsd:complexType mixed="true">
						<xsd:choice>
							<xsd:element name="Zweitstimmen">
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="prozent">
										<xsd:attribute name="Partei"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
						</xsd:choice>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="Wahltyp">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="Landtagswahl" />
						<xsd:enumeration value="Bundestagswahl" />
						<xsd:enumeration value="Europawahl" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
		</xsd:complexType>







		<!-- <xsd:complexType> </xsd:complexType> -->
	</xsd:element>
</xsd:schema>

=== DanielJosefKrueger/IntechPraktikum/InTech22/example.xml
<Wahl xsi:noNamespaceSchemaLocation="VML.xsd">
	<Wahltag>12.12.2012</Wahltag>
	<Wahlbeginn>12:12</Wahlbeginn>
	<Wahlende>12:14</Wahlende>
	<Parteien>
		<Name>Die Menschen</Name>
		<Kandidaten>
			<Name>Huaba</Name>
			<Erststimmen>2.02</Erststimmen>
			<Geburtsdatum>1.1.1900</Geburtsdatum>
			<Beruf>Huabara</Beruf>
			<Listenplatz>1</Listenplatz>
		</Kandidaten>
		<Kandidaten>
			<Name>Huaba</Name>
			<Erststimmen>-2.02</Erststimmen>
			<Geburtsdatum>1.1.1900</Geburtsdatum>
			<Beruf>Huabara</Beruf>
			<Listenplatz>1</Listenplatz>
		</Kandidaten>
		<Kandidaten>
			<Name>Huaba</Name>
			<Erststimmen>2.02</Erststimmen>
			<Geburtsdatum>1.1.1900</Geburtsdatum>
			<Beruf>Huabara</Beruf>
			<Listenplatz>1</Listenplatz>
		</Kandidaten>

	</Parteien>
	<Parteien>
		<Name>Die Dummen</Name>
		<Kandidaten>
			<Name>Kevin</Name>
			<Erststimmen>10.10</Erststimmen>
			<Geburtsdatum>1.1.2000</Geburtsdatum>
			<Beruf>Depp</Beruf>
			<Listenplatz>1</Listenplatz>
		</Kandidaten>
		<Kandidaten>
			<Name>Kevin</Name>
			<Erststimmen>10.10</Erststimmen>
			<Geburtsdatum>1.1.2000</Geburtsdatum>
			<Beruf>Depp</Beruf>
			<Listenplatz>1</Listenplatz>
		</Kandidaten>
		<Kandidaten>
			<Name>Kevin</Name>
			<Erststimmen>10.10</Erststimmen>
			<Geburtsdatum>1.1.2000</Geburtsdatum>
			<Beruf>Depp</Beruf>
			<Listenplatz>1</Listenplatz>
		</Kandidaten>
	</Parteien>

	<Wahlergebnis>
		<Zweitstimmen name="Die Dummen">20</Zweitstimmen>
		<Zweitstimmen name="Die Menschen">20.22</Zweitstimmen>
	</Wahlergebnis>




</Wahl>
