=== DanielJosefKrueger/IntechPraktikum/task_1/BPML.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!-- Diese DTD beschreibt den Aufbau der MarkUp Language zur Beschreibung von Tankstellenpreise -->
<!ENTITY AT "&#x040;">
<!ENTITY % StringElem "(#PCDATA)">
<!ENTITY % StringAttr "CDATA">
<!--<!ENTITY FOTO_j SYSTEM "JPEG" NDATA JPEG>
<!ENTITY FOTO_g SYSTEM "GIF" NDATA GIF> -->
<!ELEMENT Preisübersicht (Tankstelle+,Pächter+,Mineralölgesellschaft*,Option*)>
<!ELEMENT Tankstelle (Name,Adresse,Geodaten*,Beschreibung*,Preise)>
<!ATTLIST Tankstelle pächterID IDREF #REQUIRED>
<!ATTLIST Tankstelle gesellschaftID IDREF #REQUIRED>
<!ATTLIST Tankstelle bewertung (1|2|3|4|5|6) #IMPLIED>
<!ATTLIST Tankstelle foto NOTATION (FOTO_j|FOTO_g) #IMPLIED>
<!NOTATION FOTO_j SYSTEM "Foto">
<!NOTATION FOTO_g SYSTEM "Gif">
<!ELEMENT Name %StringElem;>
<!ELEMENT Adresse %StringElem;>
<!ELEMENT Geodaten (Längengrad,Breitengrad)>
<!ELEMENT Längengrad %StringElem;>
<!ELEMENT Breitengrad %StringElem;>
<!ELEMENT Beschreibung %StringElem;>
<!ELEMENT Preise (Preis+)>
<!ELEMENT Preis %StringElem;>
<!ATTLIST Preis kraftstoffart (E10|Super|Diesel|SuperPlus) #REQUIRED>
<!ELEMENT Pächter (#PCDATA|Name|Adresse)*>
<!ATTLIST Pächter pächterID ID #REQUIRED>
<!ELEMENT Mineralölgesellschaft (Name,Adresse,Mailadresse)>
<!ATTLIST Mineralölgesellschaft gesellschaftID ID #REQUIRED>
<!ELEMENT Mailadresse %StringElem;>
<!ELEMENT Option ANY>
<!ATTLIST Preisübersicht datum %StringAttr; #REQUIRED>

=== DanielJosefKrueger/IntechPraktikum/task_1/beispieldokument.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Dieses xml File stellt eine Preisübersicht dar für die Sprache BPML -->
<!DOCTYPE Preisübersicht SYSTEM "BPML.dtd">
<Preisübersicht datum="12.12.2012">
  <Tankstelle pächterID="P12" gesellschaftID="M12" foto="FOTO_j">
    <Name>Best Petorlium</Name>
    <Adresse>Hinterdupfing 8; 85076 München</Adresse>
    <Geodaten>
      <Längengrad>66°43'12"</Längengrad>
      <Breitengrad>66°43'12"</Breitengrad>
    </Geodaten>
    <Beschreibung>Sehr angenehme und ruhige Lage</Beschreibung>
    <Preise>
      <Preis kraftstoffart="E10">1.30</Preis>
      <Preis kraftstoffart="Super">1.350</Preis>
      <Preis kraftstoffart="Diesel">1.10</Preis>
      <Preis kraftstoffart="SuperPlus">1.40</Preis>
    </Preise>
  </Tankstelle>
  <Pächter pächterID="P12">
    Groeßter Dieselhaendler Deutschlands <Name>Dagobert Diesel</Name> in <Adresse> Dagoberthausen 5</Adresse>
  </Pächter>
  <Mineralölgesellschaft gesellschaftID="M12">
    <Name>Dagobert Oil</Name>
    <Adresse>Dagobert Planet</Adresse>
    <Mailadresse>dagobert.diesel&AT;vindiesel.de</Mailadresse>
  </Mineralölgesellschaft>
  <Option>
    Hier passt alles reis, sogar eine Tankstelle (wenn man will)
  </Option>
</Preisübersicht>
